/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ItemId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Category = IDL.Variant({
  'art' : IDL.Null,
  'clothing' : IDL.Null,
  'collectibles' : IDL.Null,
  'other' : IDL.Null,
  'toys' : IDL.Null,
  'books' : IDL.Null,
  'wands' : IDL.Null,
  'props' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Price = IDL.Int;
export const ItemCondition = IDL.Variant({
  'new' : IDL.Null,
  'veryUsed' : IDL.Null,
  'used' : IDL.Null,
  'likeNew' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : ItemId,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'description' : IDL.Text,
  'seller' : UserId,
  'category' : Category,
  'image' : IDL.Opt(ExternalBlob),
  'price' : Price,
  'condition' : ItemCondition,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'isSeller' : IDL.Bool,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'to' : UserId,
  'content' : IDL.Text,
  'from' : UserId,
  'timestamp' : IDL.Int,
});
export const PublicProfile = IDL.Record({
  'activeListings' : IDL.Vec(Item),
  'profile' : UserProfile,
});
export const CartItem = IDL.Record({ 'item' : Item, 'quantity' : IDL.Nat });
export const ShoppingCartView = IDL.Record({ 'items' : IDL.Vec(CartItem) });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([ItemId, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'clearCart' : IDL.Func([], [], []),
  'createItemListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Price,
        ItemCondition,
        Category,
        IDL.Opt(ExternalBlob),
      ],
      [ItemId],
      [],
    ),
  'deleteItemListing' : IDL.Func([ItemId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getPublicProfile' : IDL.Func([UserId], [IDL.Opt(PublicProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([ItemId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchItemsByCategory' : IDL.Func([Category], [IDL.Vec(Item)], ['query']),
  'searchItemsByCondition' : IDL.Func(
      [ItemCondition],
      [IDL.Vec(Item)],
      ['query'],
    ),
  'searchItemsByPriceRange' : IDL.Func(
      [Price, Price],
      [IDL.Vec(Item)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'updateCartItem' : IDL.Func([ItemId, IDL.Nat], [], []),
  'updateItemListing' : IDL.Func(
      [
        ItemId,
        IDL.Text,
        IDL.Text,
        Price,
        ItemCondition,
        Category,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'viewCart' : IDL.Func([], [ShoppingCartView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ItemId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Category = IDL.Variant({
    'art' : IDL.Null,
    'clothing' : IDL.Null,
    'collectibles' : IDL.Null,
    'other' : IDL.Null,
    'toys' : IDL.Null,
    'books' : IDL.Null,
    'wands' : IDL.Null,
    'props' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Price = IDL.Int;
  const ItemCondition = IDL.Variant({
    'new' : IDL.Null,
    'veryUsed' : IDL.Null,
    'used' : IDL.Null,
    'likeNew' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : ItemId,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'description' : IDL.Text,
    'seller' : UserId,
    'category' : Category,
    'image' : IDL.Opt(ExternalBlob),
    'price' : Price,
    'condition' : ItemCondition,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'isSeller' : IDL.Bool,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'to' : UserId,
    'content' : IDL.Text,
    'from' : UserId,
    'timestamp' : IDL.Int,
  });
  const PublicProfile = IDL.Record({
    'activeListings' : IDL.Vec(Item),
    'profile' : UserProfile,
  });
  const CartItem = IDL.Record({ 'item' : Item, 'quantity' : IDL.Nat });
  const ShoppingCartView = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([ItemId, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'clearCart' : IDL.Func([], [], []),
    'createItemListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Price,
          ItemCondition,
          Category,
          IDL.Opt(ExternalBlob),
        ],
        [ItemId],
        [],
      ),
    'deleteItemListing' : IDL.Func([ItemId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
    'getItem' : IDL.Func([ItemId], [IDL.Opt(Item)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getPublicProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(PublicProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([ItemId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchItemsByCategory' : IDL.Func([Category], [IDL.Vec(Item)], ['query']),
    'searchItemsByCondition' : IDL.Func(
        [ItemCondition],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'searchItemsByPriceRange' : IDL.Func(
        [Price, Price],
        [IDL.Vec(Item)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'updateCartItem' : IDL.Func([ItemId, IDL.Nat], [], []),
    'updateItemListing' : IDL.Func(
        [
          ItemId,
          IDL.Text,
          IDL.Text,
          Price,
          ItemCondition,
          Category,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'viewCart' : IDL.Func([], [ShoppingCartView], []),
  });
};

export const init = ({ IDL }) => { return []; };