/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'item' : Item, 'quantity' : bigint }
export type Category = { 'art' : null } |
  { 'clothing' : null } |
  { 'collectibles' : null } |
  { 'other' : null } |
  { 'toys' : null } |
  { 'books' : null } |
  { 'wands' : null } |
  { 'props' : null } |
  { 'syrups' : null };
export type ExternalBlob = Uint8Array;
export interface Friendship {
  'user' : UserId,
  'friend' : UserId,
  'confirmed' : boolean,
}
export interface Item {
  'id' : ItemId,
  'title' : string,
  'created' : bigint,
  'description' : string,
  'seller' : UserId,
  'category' : Category,
  'image' : [] | [ExternalBlob],
  'price' : Price,
  'condition' : ItemCondition,
}
export type ItemCondition = { 'new' : null } |
  { 'veryUsed' : null } |
  { 'used' : null } |
  { 'likeNew' : null };
export type ItemId = bigint;
export interface Message {
  'id' : MessageId,
  'to' : UserId,
  'content' : string,
  'from' : UserId,
  'timestamp' : bigint,
}
export type MessageId = bigint;
export type Price = bigint;
export interface PublicProfile {
  'activeListings' : Array<Item>,
  'profile' : UserProfile,
}
export interface ShoppingCartView { 'items' : Array<CartItem> }
export type UserId = Principal;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'isSeller' : boolean,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wand {
  'id' : string,
  'owner' : UserId,
  'name' : string,
  'createdAt' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[UserId], undefined>,
  'addToCart' : ActorMethod<[ItemId, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseItems' : ActorMethod<[], Array<Item>>,
  'clearCart' : ActorMethod<[], undefined>,
  'createItemListing' : ActorMethod<
    [string, string, Price, ItemCondition, Category, [] | [ExternalBlob]],
    ItemId
  >,
  'createWand' : ActorMethod<[string], Wand>,
  'deleteItemListing' : ActorMethod<[ItemId], undefined>,
  'deleteWand' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConfirmedFriends' : ActorMethod<[], Array<UserId>>,
  'getConversation' : ActorMethod<[UserId], Array<Message>>,
  'getFriendWands' : ActorMethod<[UserId], Array<Wand>>,
  'getItem' : ActorMethod<[ItemId], [] | [Item]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getMyListings' : ActorMethod<[], Array<Item>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<Friendship>>,
  'getPublicProfile' : ActorMethod<[UserId], [] | [PublicProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWand' : ActorMethod<[string], [] | [Wand]>,
  'getWands' : ActorMethod<[], Array<Wand>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectFriendRequest' : ActorMethod<[UserId], undefined>,
  'removeFromCart' : ActorMethod<[ItemId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchItemsByCategory' : ActorMethod<[Category], Array<Item>>,
  'searchItemsByCondition' : ActorMethod<[ItemCondition], Array<Item>>,
  'searchItemsByPriceRange' : ActorMethod<[Price, Price], Array<Item>>,
  'sendFriendRequest' : ActorMethod<[UserId], undefined>,
  'sendMessage' : ActorMethod<[UserId, string], MessageId>,
  'updateCartItem' : ActorMethod<[ItemId, bigint], undefined>,
  'updateItemListing' : ActorMethod<
    [
      ItemId,
      string,
      string,
      Price,
      ItemCondition,
      Category,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateWand' : ActorMethod<[string, string], undefined>,
  'viewCart' : ActorMethod<[], ShoppingCartView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];